/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnsemblesRouteImport } from './routes/ensembles'
import { Route as MateriauxRouteImport } from './routes/materiaux'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as TechRouteImport } from './routes/tech'
import { Route as EnsemblesIdRouteImport } from './routes/ensembles.$id'
import { Route as ProduitsIdRouteImport } from './routes/produits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsemblesRoute = EnsemblesRouteImport.update({
  id: '/ensembles',
  path: '/ensembles',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriauxRoute = MateriauxRouteImport.update({
  id: '/materiaux',
  path: '/materiaux',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsemblesIdRoute = EnsemblesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnsemblesRoute,
} as any)
const ProduitsIdRoute = ProduitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ensembles': typeof EnsemblesRouteWithChildren
  '/materiaux': typeof MateriauxRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/tech': typeof TechRoute
  '/ensembles/$id': typeof EnsemblesIdRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ensembles': typeof EnsemblesRouteWithChildren
  '/materiaux': typeof MateriauxRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/tech': typeof TechRoute
  '/ensembles/$id': typeof EnsemblesIdRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ensembles': typeof EnsemblesRouteWithChildren
  '/materiaux': typeof MateriauxRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/tech': typeof TechRoute
  '/ensembles/$id': typeof EnsemblesIdRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ensembles'
    | '/materiaux'
    | '/produits'
    | '/tech'
    | '/ensembles/$id'
    | '/produits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ensembles'
    | '/materiaux'
    | '/produits'
    | '/tech'
    | '/ensembles/$id'
    | '/produits/$id'
  id:
    | '__root__'
    | '/'
    | '/ensembles'
    | '/materiaux'
    | '/produits'
    | '/tech'
    | '/ensembles/$id'
    | '/produits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnsemblesRoute: typeof EnsemblesRouteWithChildren
  MateriauxRoute: typeof MateriauxRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  TechRoute: typeof TechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensembles': {
      id: '/ensembles'
      path: '/ensembles'
      fullPath: '/ensembles'
      preLoaderRoute: typeof EnsemblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiaux': {
      id: '/materiaux'
      path: '/materiaux'
      fullPath: '/materiaux'
      preLoaderRoute: typeof MateriauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensembles/$id': {
      id: '/ensembles/$id'
      path: '/$id'
      fullPath: '/ensembles/$id'
      preLoaderRoute: typeof EnsemblesIdRouteImport
      parentRoute: typeof EnsemblesRoute
    }
    '/produits/$id': {
      id: '/produits/$id'
      path: '/$id'
      fullPath: '/produits/$id'
      preLoaderRoute: typeof ProduitsIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
  }
}

interface EnsemblesRouteChildren {
  EnsemblesIdRoute: typeof EnsemblesIdRoute
}

const EnsemblesRouteChildren: EnsemblesRouteChildren = {
  EnsemblesIdRoute: EnsemblesIdRoute,
}

const EnsemblesRouteWithChildren = EnsemblesRoute._addFileChildren(
  EnsemblesRouteChildren,
)

interface ProduitsRouteChildren {
  ProduitsIdRoute: typeof ProduitsIdRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsIdRoute: ProduitsIdRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnsemblesRoute: EnsemblesRouteWithChildren,
  MateriauxRoute: MateriauxRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  TechRoute: TechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
